# Generated by Django 5.1.1 on 2024-09-05 18:28

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', ckeditor.fields.RichTextField()),
                ('phone_number', models.CharField(max_length=255)),
                ('picture', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', ckeditor.fields.RichTextField()),
                ('degree', models.CharField(choices=[('daytime', 'kundizgi'), ('part_time', 'sirtqi'), ('evning', 'Kechgi')], max_length=255)),
                ('dirictor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.director')),
            ],
        ),
    ]
