# Generated by Django 5.1.1 on 2024-09-05 18:32

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('uz', "o'zbek tili"), ('ru', 'rus tili'), ('en', 'inglis tili')], max_length=255)),
                ('body', ckeditor.fields.RichTextField()),
                ('education_type', models.CharField(choices=[('daytime', 'kundizgi'), ('part_time', 'sirtqi'), ('evning', 'Kechgi')], max_length=16)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.faculty')),
            ],
        ),
    ]
